### PR TITLE
[FRAM-2] added field for tel and mailto

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**
https://github.com/user-attachments/assets/10f51d3d-6274-4fd8-9518-f7ca5ce2b0ba

### CODE REVIEW

**Comment by trippd6** [comment]
The old version of framework had a button that would take you to the referenced record... for example if you have a assigned to: friend that references a user record, there is a button that takes you to that record: 

image

We need to add that back... i will add a story for that...

Email and telephone number fields should have a similar button, with unique icons, that provide the mailto: or tel: functionality. 

Lets remove the functionality from the table, and just have it on the field on the record view, with an explicit button.

**Comment by trippd6** [comment]
I added back the view related record button in main... please make similar buttons for call and email... may want to make the whole tool tip + button + icon its own reusable component and use it for tel, mail and the go to related record button I just created.

**Comment by BhuvaneshPatil** [comment]
I removed the functionality of taking to record upon clicking on the row of table.
Do we have to provide any other way of viewing the record from table directly? If yes, what it will be?

**Comment by trippd6** [comment]
I'm not sure I understand the question... when you click on a row, it should take you to the record... all the fields are displayed there... and we need a call/email button next to the relevant fields...

**Comment by trippd6** [comment]
the button should be added to email.js inside the edit function... a button after the field... see reference.jsx as an example... make sure to get the latest main.

**Comment by BhuvaneshPatil** [comment]
My original question is about - 
When we click on row of table, it takes us to record.
After adding email and phone call icon, if I click on the link/button the default behaviour of row will also happen.

https://github.com/user-attachments/assets/bc34fb19-12e0-4494-acb2-4b7ae3626fbd

For example in above video when I clicked on call button it performed action of `tel` but also took me to record page

**Comment by trippd6** [comment]
The button should only exist on the edit page and should not exist in the table at all.

**Comment by BhuvaneshPatil** [comment]
okay. Got it.

**Comment by BhuvaneshPatil** [comment]
Changes are ready

https://github.com/user-attachments/assets/56034c44-cdd8-42a8-92e3-de7c9b4bb635

**Pull request merged**
