### PR TITLE
Fram 11

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**
updated video in ticket - https://vacso.atlassian.net/browse/FRAM-11?focusedCommentId=10026

### CODE REVIEW

**Comment by BhuvaneshPatil** [comment]
Let me know where you want to keep viewer's component on the page.

**Comment by trippd6** [comment]
@BhuvaneshPatil  overall, looks good. some tweaks:

- Move the component to the same row as the record header. Justify it right.
- Move all the data pulling logic for the activeviewers component into that component.
- Switch from callbackend to useBackend, which uses tanstack query under the hood. To force it to refresh every 5 seconds, use a reload usestate, and pass it to reload of the usebackend. This will force it to update when the usestate increments via an interval in a useeffect.
- Inside view.js on the backend, feel free to use knex directly. it is available to every class via this.knex. This way you can request just the relevant rows, and use more advanced queries then rowsget provides. 

Let me know if you have any questions. If you have an issues let me know and we can either discuss more, or I can refactor the code my self. 

Thanks!

**Comment by trippd6** [comment]
also please merge the latest main into this branch.

**Comment by BhuvaneshPatil** [comment]
- changed the position of Viewers component, moved to header
- moved logic inside the component

**Comment by trippd6** [comment]
@BhuvaneshPatil 

This all looks good. I pushed a commit into your branch just to tweak some spacing so the page doesn't move when the active viewers data comes in.

can we combine the two usebackend calls into one that updates that this user is active and gets a list of all the active users?

**Comment by Bhuvanesh-Fictiv** [comment]
Yeah sounds like good idea.
I will update the code

**Pull request merged**
