### PR TITLE
[FRAM-5] added sidebar

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**

### CODE REVIEW

**Comment by trippd6** [comment]
Overall, I like it. Some feedback:

- The change adds /components/ui/button.jsx. But there is already /src/components/ui/button.jsx. Everything should be moved to one place.
- Move the arrow button that collapses the sidebar to the bottom of the screen/sidebar, so it doesn't overlap table/record headers
- Make the default state of all the sections of the menu to be expanded.
- Change the word "Account" to the users name
- When viewing a record with a child/related table that has no records, there is a scroll bar that is in the middle of the screen. See my screenshot. Either there shouldn't be a scroll bar at all, or the scroll bar should be at the right edge of the window.

Let me know if you have any questions.

image

**Comment by BhuvaneshPatil** [comment]
updated code

**Comment by trippd6** [comment]
@BhuvaneshPatil 

1. the little expand/collapse arrows are now backwards... if you compare them to https://ui.shadcn.com/docs/components/sidebar, they should be pointed down when the sectinon is expanded, to the side when collapsed.
2. When I'm logged in as admin, I expect to see "admin" at the bottom, but I'm still seeing account.

**Comment by BhuvaneshPatil** [comment]
For admin issue I have made changes on backend as well. I will raise PR for that. Basically we need to send user email with token when logging in

**Comment by BhuvaneshPatil** [comment]
I will check the arrow issue.

**Comment by trippd6** [comment]
@BhuvaneshPatil I cleaned some things up. I fixed the username/email thing (they were already available in the userstore in tokenfields. I'm going to merge this and call it good.

**Pull request merged**
