### PR TITLE
[FRAM-9] Reference record search

### PR DESCRIPTION
**Pull request by BhuvaneshPatil**

### CODE REVIEW

**Comment by trippd6** [comment]
@BhuvaneshPatil 

1. The tooltip for the new button needs to be updated to "Search for related record"
2. BUG: I go to a ticket, I go to the requester field, click the new record search button, I start typing in the full name field, and I get the below error. 

image

**Comment by trippd6** [comment]
On the bug, i'm looking at it... its a nuqs thing...

**Comment by trippd6** [comment]
@BhuvaneshPatil 

We're using nuq's to store the state of the table in the URL and history, so when you hit the back button you see the table in the same state it was when you were last on that page. Also you can share urls with others and they will see the same filters, etc. This state is global on the display components. When using this new related record search, when you searched it also triggered the child table search on the page, by default comments. since the column names didn't match up, it threw errors.

What I did was disabled nuqs inside the related record search... but I had to do it by creating a custom hook that uses usequerystate (nuqs) or standard react usestate, depending on the requirements.

I pushed a commit to fix the bug. I also fixed the tooltip. Please review, test, and let me know if you have any questions or concerns.

**Comment by BhuvaneshPatil** [comment]
Thanks @trippd6. I was thinking in the same direction.

**Comment by BhuvaneshPatil** [comment]
Changes looks good to me

**Pull request merged**
